In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [6]:
df.shape

(8, 4)

In [7]:
df.describe()

test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [9]:
df['experience'].isna().sum()  # to check the number of nan in experience column

2

In [10]:
#fill the nan values of experience to zero
#df.experience = df.experience.fillna('zero')
df['experience'] = df['experience'].fillna('Zero')

df['experience']


0      Zero
1      Zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [11]:
type(df['experience'])

pandas.core.series.Series

In [12]:
#fill the nan value of test score as a median value or mean value

df['test_score(out of 10)'].fillna(value=df['test_score(out of 10)'].median(), inplace=True)

In [13]:
# again check the dataset for nay null value
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      object 
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [14]:
!pip install  word2number  # install word2number package

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=6333bfae97770fe4c5558bccd5295a1d26fe76937c6426018fd0a63882de7863
  Stored in directory: /root/.cache/pip/wheels/4b/c3/77/a5f48aeb0d3efb7cd5ad61cbd3da30bbf9ffc9662b07c9f879
Successfully built word2number


In [15]:

# experience column have number in text , convert into numericals
from word2number import w2n

#res = w2n.word_to_num('one')
#res
#df.experience = df.experience.apply(w2n.word_to_num)       # can be done this way also

df['experience'] = df['experience'].apply(w2n.word_to_num)


In [16]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      int64  
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 384.0 bytes


In [18]:
x = df.iloc[0:8 , 0:3]
x.shape

(8, 3)

In [19]:
x= df.drop('salary($)',axis =1)    # either way we can split the features and target
x.shape

(8, 3)

In [20]:
y= df['salary($)']
y.shape

(8,)

In [21]:
# split the data into training and test data
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(x,y)

In [22]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(6, 3)
(2, 3)
(6,)
(2,)


In [23]:
# lets build a model

In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [25]:
# fit the model

model.fit(xtrain , ytrain)

LinearRegression()

In [26]:
# tets the model
ypred = model.predict(xtest)

In [27]:
#calculate the accuracy using R2

from sklearn.metrics import r2_score
r2result = r2_score(ytest, ypred)
r2result

0.3814447081194211

In [28]:
# create a list to fetch the accuracy result
accuracy_list=[]
for i in range(1000):
  xtrain , xtest, ytrain , ytest = train_test_split(x,y,train_size=0.8 ,random_state=i)
  model =LinearRegression()
  model.fit(xtrain , ytrain)
  ypred = model.predict(xtest)
  r2result = r2_score(ytest, ypred)
  accuracy_list.append(r2result)

In [29]:
accuracy_list

[0.3814447081194211,
 0.8515192720986251,
 0.8159486689885806,
 0.924427136462572,
 0.17760298275080622,
 0.8515192720986248,
 0.8167827818183632,
 -17.688208905655845,
 0.9606461804676223,
 0.9566786526224457,
 0.3493545891913713,
 0.38144470811942055,
 -15.877716374972685,
 0.8159486689885809,
 0.06266896871484517,
 0.34935458919136975,
 0.27310355973040124,
 -8.694392415972386,
 -0.11107260610819525,
 0.8159486689885802,
 0.9244271364625727,
 0.8515192720986248,
 0.8854262054139517,
 0.17760298275080133,
 0.9244271364625731,
 0.9047826768488456,
 0.856365786429019,
 0.8515192720986253,
 0.3814447081194211,
 0.9566786526224456,
 0.8854262054139518,
 0.8159486689885805,
 0.8830011998552887,
 -2.183874957833533,
 0.9047826768488458,
 -17.68820890565591,
 0.17760298275080277,
 -17.68820890565591,
 0.8515192720986248,
 -9.575872458761951,
 0.9566786526224458,
 0.06266896871484462,
 0.9321989859471912,
 0.8563657864290184,
 -17.68820890565578,
 -17.688208905655884,
 0.8830011998552881,
 0

In [30]:
np.max(accuracy_list)

0.9606461804676225

In [31]:
# to find the index of the max value
np.argmax(accuracy_list)

276

In [32]:
# the previous result shows the random value 276 has the max accuracy value , so create model with that value

xtrain , xtest, ytrain , ytest = train_test_split(x,y,train_size=0.8 ,random_state=276)
model =LinearRegression()
model.fit(xtrain , ytrain)
ypred = model.predict(xtest)
r2result = r2_score(ytest, ypred)
r2result

0.9606461804676225

In [33]:
# test the model with your own value   sample 1
model.predict([[2,9,6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([54023.42770408])

In [34]:
# test the model with your own value   sample 2
model.predict([[12,10,10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([90648.84841286])

In [35]:
# to save this model and test anyday anytime
# this model needs to be saved to a file
import joblib
joblib.dump(model , 'multilinear-salary.pkl')

['multilinear-salary.pkl']

In [36]:
# how to use the saved model later
# first load the model to your environment
mymodel = joblib.load('/content/multilinear-salary.pkl' )

In [37]:
mymodel.predict([[12,10,10]])  # test your model

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([90648.84841286])